name: Helm Chart Test

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/helm-test.yaml'
  pull_request:

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up KinD cluster
      uses: helm/kind-action@v1.7.0

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Create halo namespace
      run: kubectl create namespace halo

    - name: Build chart dependencies
      run: helm dependency build ./charts/halo

    - name: Install Halo chart
      run: |
        helm install halo ./charts/halo \
          -n halo \
          -f ./charts/halo/values.yaml

    - name: Wait for pods to be ready
      run: |
        kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=halo -n halo --timeout=180s

    - name: Show Halo pod logs
      run: |
        kubectl logs -l app.kubernetes.io/name=halo -n halo

    - name: Check Halo service status
      run: kubectl get svc -n halo
