name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/halo/Chart.yaml"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # —— 新增这一步：如不存在则建分支 —— 
      - name: Ensure gh-pages branch exists
        run: |
          # 尝试 fetch；若远端无此分支也不要报错
          git fetch origin gh-pages || true
          # 本地切换到 gh-pages，若不存在则创建孤儿分支
          git checkout gh-pages || git checkout --orphan gh-pages
          # 提交空改动（若全新分支），并推送
          git commit --allow-empty -m "Initialize gh-pages branch" || true
          git push origin gh-pages
          # 切回主分支继续
          git checkout main

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          pages_branch: gh-pages    # 默认就是 gh-pages，可省略
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
